# Generated by Django 5.0.4 on 2024-04-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='facebook_profile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postal_zip_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state_province_region',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter_handle',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website_url',
        ),
    ]
