# Generated by Django 5.0.4 on 2024-04-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='address line 1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='company name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_profile',
            field=models.URLField(blank=True, verbose_name='Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=30, verbose_name='Instagram handle'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_profile',
            field=models.URLField(blank=True, verbose_name='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_zip_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='postal/zip code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='preferences'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state_province_region',
            field=models.CharField(blank=True, max_length=100, verbose_name='state/province/region'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=15, verbose_name='Twitter handle'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='website URL'),
        ),
    ]
